### ISSUE TITLE
Typed URL with Friends installed into another website's `/friends` and got redirected to wpfriends.at

### ISSUE THREAD

**Issue by HammyHavoc** [akirk/friends#146]
Hi,

I put https://hammyhavoc.com into https://bryandesrosiers.com, and Bryan has also done the inverse, and we just get redirected.

I get redirected to https://wpfriends.at/follow-me/?url=https%3A%2F%2Fhammyhavoc.com

Is this expected behaviour? E.g. are we instead meant to add each other via the `/wp-admin` area of our respective site in the Friends plugin itself?

**Comment by akirk** [comment]
This is not expected behavior. In this case, it looks like Cloudflare strips the [`Link` headers from the HTTP HEAD response](https://github.com/akirk/friends/blob/019c2b9744d6b6db9e5957e10427ad4b28a0e560/includes/class-friends.php#L941) which [are retrieved when someone clicks the button](https://github.com/akirk/friends/blob/019c2b9744d6b6db9e5957e10427ad4b28a0e560/includes/class-blocks.php#L372).

The intended behavior is for your own site to [check if their site has the Friends plugin through the HTTP header](https://github.com/akirk/friends/blob/019c2b9744d6b6db9e5957e10427ad4b28a0e560/includes/class-blocks.php#L372) and [then redirect them to their own "Add friend" page](https://github.com/akirk/friends/blob/019c2b9744d6b6db9e5957e10427ad4b28a0e560/includes/class-blocks.php#L382).

In #160, I have added code that also checks the HTML source, fixing this particular issue. 

Overall, I am not sure this `/friends` follow me approach is the best, it's a bit of a crutch that I don't have a really better solution for yet.

**Comment by HammyHavoc** [comment]
Nice catch with figuring out it was CF!

I'll preface this comment with being a major fan of the 'Now page' concept, and other quirky IndieWeb ideas.

I really like the potential of `/friends` (or a shortcode embedded into another page such as `/links` for example) as a way of bringing discovery to individual websites that's relatively pain-free to implement once people are already using it to follow others. The user-level curation is a lovely antithesis to the algorithmic "recommended to follow" of Twitter, or "recommended" of YouTube. Might also be interesting to allow people to filter or browse through lists on a page, depending on how granular people feel they need to go if they have a lot of recommendations.

The sensible alternative might be splitting it out into defaults of `/friends` and `/follow`, and if people don't want to follow the would-be standard, they can either change the Pages/slugs, add shortcodes for classes wherever they see fit, or even disable the functionality.

A `/follow` page would hypothetically be intended to provide a means to follow on-page via ActivityPub, but also list other places that content is syndicated to, e.g. the usual suspects of Twitter, Facebook, Instagram et cetera, for anybody who isn't currently a fediverse user, providing the information, but not emphasizing it by any means. I see similar with musicians pushing people to their WooCommerce or Bandcamp, but elsewhere on the site, mentioning, but putting _far_ less attention on, the usual streaming platforms, so that their audience can go that route if they need to.

---

In an ideal world, on Android at least, a link might be able to open a future PWA to add a feed/send a friend request.
