### ISSUE TITLE
Present post author avatar instead of favicon in `/friends`

### ISSUE THREAD

**Issue by HammyHavoc** [akirk/friends#156]
Displaying the site favicon doesn't make sense when also mentioning the username of the person who posted it.

**Comment by HammyHavoc** [comment]
Perhaps what makes more sense is falling back to the favicon if the author doesn't have an avatar set, but likewise, if there's no favicon, conditional logic to not present a broken image.

**Comment by akirk** [comment]
I like the idea but this would only work if we extend the RSS feed since the author gravatar is not usually supplied in the feed.

For a friend request, [the (gr)avatar is already transmitted](https://github.com/akirk/friends/blob/828fb71cd995e023409832d1a471341764fe1a49/includes/class-rest.php#L396).

For ActivityPub the avatar is used in favor of the favicon since #142.

For this reason I am tempted to give it a wontfix for now, what do you think?

**Comment by HammyHavoc** [comment]
`wontfix` works for me! :- )
