### ISSUE TITLE
Hide `Friend's URL` text field on `/friends` until `Send Request` or similar is clicked

### ISSUE THREAD

**Issue by HammyHavoc** [akirk/friends#157]
Would tidy up the UI to not have an editable text field there all the time.

**Comment by akirk** [comment]
Hm, I am a little hesitant here since I think it can be helpful to see that you can enter something. So far I didn't see that external friends page as a page that someone who already uses the Friends plugin would commonly visit. They could use the browser extension #21 or bookmarklet:

<img width="541" alt="Screenshot 2023-01-02 at 06 59 43" src="https://user-images.githubusercontent.com/203408/210199073-f4fa90e5-2b6f-48db-a499-2246a176a8aa.png">

Or enter the URL directly. And at some point discover new friends through your friends:
- #19

For your own page, since it's just an editable page, you could do this yourself with the Toggles block like this:

<img width="466" alt="Screenshot 2023-01-02 at 06 48 20" src="https://user-images.githubusercontent.com/203408/210198447-23eeabc1-ffcd-4e76-8aaf-31b90b4b7496.png">

Which results in this:
![toggles-follow-me](https://user-images.githubusercontent.com/203408/210198539-9c2d8172-325e-4958-a7bb-771a348502c6.gif)

I'll close this in favor of #159 to have a more focussed discussion there.

**Comment by HammyHavoc** [comment]
I should have clarified that better, sorry! The Issue was regarding `/friends` when viewed as an admin, i.e. your feed view. Think we already addressed it more or less with https://github.com/akirk/friends/issues/158! :- )
