### ISSUE TITLE
Uncaught Error: You tried to opt-in to unstable APIs

### ISSUE THREAD

**Issue by aaronjorbin** [akirk/friends#264]
This is using Gutenberg 16.9.0, WordPress 6.5-alpha-57027,  and Friends 2.8.2. 

My guess is that this is related to https://github.com/WordPress/gutenberg/pull/55182 https://github.com/akirk/friends/tree/main/libs/blocks-everywhere will need to be updated. 

```
Error: You tried to opt-in to unstable APIs without confirming you know the consequences. This feature is only for JavaScript modules shipped with WordPress core. Please do not use it in plugins and themes as the unstable APIs will removed without a warning. If you ignore this error and depend on unstable features, your product will inevitably break on the next WordPress release.
__dangerousOptInToUnstableAPIsOnlyForCoreModules(../../packages/private-apis/src/implementation.js:107)
		throw new Error(
294(https://aaron.jorb.in/wp-content/plugins/friends/libs/blocks-everywhere/build/index.min.js:24)

r(https://aaron.jorb.in/wp-content/plugins/friends/libs/blocks-everywhere/build/index.min.js:42)

[anonymous](https://aaron.jorb.in/wp-content/plugins/friends/libs/blocks-everywhere/build/index.min.js:42)

r.O(https://aaron.jorb.in/wp-content/plugins/friends/libs/blocks-everywhere/build/index.min.js:42)

[anonymous](https://aaron.jorb.in/wp-content/plugins/friends/libs/blocks-everywhere/build/index.min.js:42)

[anonymous](https://aaron.jorb.in/wp-content/plugins/friends/libs/blocks-everywhere/build/index.min.js:42)
```

**Comment by akirk** [comment]
Thanks for the pointer! I need to upgrade blocks-everywhere to https://github.com/Automattic/blocks-everywhere/pull/193 (in my defense, it was only released 6 hrs ago :) )

I am currently unable to test, could you just elaborate on the consequences? Does it completely break everything?

**Comment by aaronjorbin** [comment]
It's hard to tell what is or is not broken for me as I am not much of a power user of friends yet. I can tell you that the main `/friends` page loads. Sorry for not being able to provide a better bug report.

**Comment by lordmatt** [comment]
Can confirm seeing this. Replies seem to be broken. The reply text box is grayed out and inactive.

**Comment by akirk** [comment]
Until I figure things out, you can turn off Gutenberg on the Frontend in Settings:

<img width="514" alt="Screenshot 2023-11-12 at 06 32 17" src="https://github.com/akirk/friends/assets/203408/ac7342cc-967d-446c-aadc-d3ae1c4b32fc">

Unfortunately it is not as easy as just upgrading Blocks Everywhere library since it is [now locked to the latest version of Gutenberg](https://github.com/Automattic/blocks-everywhere/pull/193) which is likely different from the one which comes with WordPress. So either I completely remove this, or I ship multiple versions of Blocks Everywhere.

Things have been busy at work, I'm hoping to publish a new version with a solution within the week.
