### ISSUE TITLE
Feature: ability to remove a feed/friend

### ISSUE THREAD

**Issue by lucasgonze** [akirk/friends#275]
After much hunting around in the UI, I have given up on finding where I can remove a feed/friend. There seems to be no feature for it.

Request: add ability to remove a friend.

**Comment by akirk** [comment]
Sorry for the bad discoverability. There are multiple places:

On the "Friends & Requests" page, reachable like this:
<img width="179" alt="Screenshot 2023-11-28 at 21 40 20" src="https://github.com/akirk/friends/assets/203408/9660b952-bd58-413e-87e3-e539a027e2b2">
And then when you hover over the person, there is an "Unfriend":
<img width="292" alt="Screenshot 2023-11-28 at 21 39 28" src="https://github.com/akirk/friends/assets/203408/0c5e9f0b-339f-4667-b2d6-09b3a02a19c9">

There is also an "Unfriend" link at the bottom of the "Friend Edit" page:
<img width="838" alt="Screenshot 2023-11-28 at 21 38 35" src="https://github.com/akirk/friends/assets/203408/78213698-5aac-4f9e-8cc7-16db68b7c7bd">

This will lead you to a confirmation dialog (I just noticed I need to update the copy since #215):
<img width="257" alt="Screenshot 2023-11-28 at 21 41 28" src="https://github.com/akirk/friends/assets/203408/da46b561-a030-4954-8fd5-fab2ee1b5529">

Do you have suggestions where this Unfriend should also be added?
